# Generated by Django 5.2.4 on 2025-07-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numbet',
            new_name='phone_number',
        ),
    ]
